### ISSUE TITLE
1.66 cups not rendering as 1 ⅔

### ISSUE THREAD

**Issue by johnj24** [nystudio107/craft3-recipe#13]
Hey, Andrew. It looks like there might be an issue with 1.66 not rendering as a fraction on the front-end. Our template is rendering as: `1 66667⁄100000`

1.25, 1.5, 1.75 all render fine as fractions. However, I've tried `1.66, 1.67, 1.667, 1.66667` and all of those output one of those long fractions.

**Comment by johnj24** [comment]
Hi, Andrew. Any chance you've had time to look into this?

**Comment by vaughn-taylor** [comment]
Hi Andrew. I noticed that this has been sitting stale since Oct, 2019. Do you have an recommendations on how to deal with this? I need to do 2-2/3 cups and none of the decimals that @johnj24 mentioned work.

**Comment by vaughn-taylor** [comment]
@johnj24 I'm not sure if you're still looking for a fix, but I found a solution that works for me here: https://github.com/nystudio107/craft-recipe/compare/v1...vaughn-taylor:patch-2

**Comment by khalwat** [comment]
@vaughn-taylor  So the reason this fails is a result of how floating point numbers are represented internally. When you do any kind of floating point arithmetic operation, including addition and subtraction, the result is an _approximation_.

Thus as per: https://www.php.net/manual/en/language.types.float.php#113703

...the mantissa should be `.66` but internally after the substraction here: https://github.com/nystudio107/craft-recipe/blob/v1/src/models/Recipe.php#L403

...it's represented by something kinda close to `.66` such as `.6599999` so the comparison fails. It works when you typecast it to a string because this cause PHP to internally round the number.

But I think it's better to be explicit about it, as fixed in: https://github.com/nystudio107/craft-recipe/commit/4978b70c87237554ee6284b55f826e957fceccf4

**Comment by vaughn-taylor** [comment]
Thanks Andrew. I knew that my solution was not correct, and I just learned the word "mantissa" ;)

**Comment by johnj24** [comment]
Thank you @vaughn-taylor and @khalwat for all the assistance on this.
